# -*- coding: utf-8 -*-
"""final_defence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s8Bq17wcnFT4oAU3xlPzvMlYiC1dd31P
"""

pip install pandas

import pandas as pd

# Load the data from the CSV file into a DataFrame
df = pd.read_csv('/content/feeds.csv')

columns_to_delete = ['latitude', 'longitude','elevation','status']
df.drop(columns=columns_to_delete, axis=1, inplace=True)

df.to_csv('updated_file_path.csv', index=False)

updated_df = pd.read_csv('updated_file_path.csv')

# Display the contents of the updated DataFrame
print(updated_df)

# Load the data from the CSV file into a DataFrame
df = pd.read_csv('updated_file_path.csv')

# Drop rows containing NaN values
df.dropna(inplace=True)

# Save the updated DataFrame to a new CSV file
df.to_csv('updated_file_path.csv', index=False)

updated_df = pd.read_csv('updated_file_path.csv')

# Display the contents of the updated DataFrame
print(updated_df)

pip install pandas numpy matplotlib

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the updated data from the CSV file into a DataFrame
df = pd.read_csv('updated_file_path.csv')

# Drop the 'entry_id' column
df.drop(columns=['entry_id'], inplace=True)

# Rename columns to desired names
df.rename(columns={'field1': 'nitrogen', 'field2': 'phosphorus', 'field3': 'potassium',
                   'field4': 'soil_moisture', 'field5': 'humidity', 'field6': 'temperature'},
          inplace=True)

# Calculate descriptive statistics for numerical columns
descriptive_stats = df.describe()

# Print the descriptive statistics
print(descriptive_stats)

# Plot histograms for all numerical columns
df.hist(bins=10, figsize=(12, 8))
plt.show()

# Plot box plots for all numerical columns
df.boxplot(figsize=(12, 8))
plt.show()

# Plot a scatter plot between 'nitrogen' and 'phosphorus'
plt.scatter(df['nitrogen'], df['phosphorus'])
plt.xlabel('Nitrogen')
plt.ylabel('Phosphorus')
plt.title('Scatter Plot: Nitrogen vs. Phosphorus')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load the updated data from the CSV file into a DataFrame
df = pd.read_csv('updated_file_path.csv')

# Drop the 'entry_id' column
df.drop(columns=['entry_id'], inplace=True)

# Rename columns to desired names
df.rename(columns={'field1': 'nitrogen', 'field2': 'phosphorus', 'field3': 'potassium',
                   'field4': 'soil_moisture', 'field5': 'humidity', 'field6': 'temperature'},
          inplace=True)

# Convert 'created_at' to datetime if it's not already in that format
df['created_at'] = pd.to_datetime(df['created_at'])

# Set 'created_at' as the index for time-based plotting
df.set_index('created_at', inplace=True)

# Plot all fields in a single graph (line plot)
df.plot(figsize=(12, 8))
plt.xlabel('Time')
plt.ylabel('Values')
plt.title('Variation of Fields Over Time')
plt.legend(loc='upper left')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load the updated data from the CSV file into a DataFrame
df = pd.read_csv('updated_file_path.csv')

# Drop the 'entry_id' column
df.drop(columns=['entry_id'], inplace=True)

# Rename columns to desired names
df.rename(columns={'field1': 'nitrogen', 'field2': 'phosphorus', 'field3': 'potassium',
                   'field4': 'soil_moisture', 'field5': 'humidity', 'field6': 'temperature'},
          inplace=True)

# Convert 'created_at' to datetime if it's not already in that format
df['created_at'] = pd.to_datetime(df['created_at'])

# Set 'created_at' as the index for time-based plotting
df.set_index('created_at', inplace=True)

# Plot all fields in a single graph (line plot)
df.plot(figsize=(12, 8))
plt.xlabel('Time')
plt.ylabel('Values')
plt.title('Variation of Fields Over Time')
plt.legend(loc='upper left')
plt.show()